import os

path = "C:/Users/mousongzhe/NoteBook/agent_reward_report.html"

content = (
'<section id="sandbox-design">\n'
'<h2>4. 针对 Sandbox Agent 的奖励模型设计方案</h2>\n'
'\n'
'<h3>4.1 数据生成策略</h3>\n'
'<p>利用现有 sandbox 环境，可以低成本地生成大规模标注数据：</p>\n'
'\n'
'<h4>轨迹采样与自动标注</h4>\n'
'<ol>\n'
'  <li><strong>多样化采样</strong>：对每个导航任务，使用不同温度参数（\\( T \\in \\{0.3, 0.7, 1.0, 1.3\\} \\)）各采样 \\( K \\) 条轨迹，确保覆盖好/差轨迹的分布</li>\n'
'  <li><strong>自动标注</strong>：对每条轨迹运行 <code>score_trace()</code>，获得六维度分数和综合分数</li>\n'
'  <li><strong>数据过滤</strong>：保留综合分数 \\( &lt; 0.2 \\)（差轨迹）和 \\( &gt; 0.6 \\)（好轨迹）的样本，丢弃中间区域的模糊样本</li>\n'
'</ol>\n'
'\n'
'<h4>偏好对构造</h4>\n'
'<p>对同一导航任务的轨迹集合，按以下规则构造偏好对：</p>\n'
'<pre><code class="language-python">def construct_preference_pairs(trajectories_by_task, score_threshold=0.3):\n'
'    pairs = []\n'
'    for task_id, traj_scores in trajectories_by_task.items():\n'
'        sorted_trajs = sorted(traj_scores, key=lambda x: x[1], reverse=True)\n'
'        for i, (tau_pos, score_pos) in enumerate(sorted_trajs):\n'
'            for tau_neg, score_neg in sorted_trajs[i+1:]:\n'
'                if score_pos - score_neg >= score_threshold:\n'
'                    pairs.append({\n'
'                        "prompt": task_id,\n'
'                        "trajectory_pos": tau_pos,\n'
'                        "trajectory_neg": tau_neg,\n'
'                        "score_diff": score_pos - score_neg,\n'
'                        "step_scores_pos": tau_pos.step_scores,\n'
'                        "step_scores_neg": tau_neg.step_scores,\n'
'                    })\n'
'    return pairs</code></pre>\n'
'\n'
'<h4>数据格式</h4>\n'
'<pre><code class="language-json">{\n'
'  "task_id": "nav_task_0042",\n'
'  "prompt": "导航到厨房并检查冰箱状态",\n'
'  "trajectory_tokens": [\n'
'    {"role": "assistant", "content": "&lt;tool_call&gt;move_forward(distance=2.0)&lt;/tool_call&gt;"},\n'
'    {"role": "tool", "content": "moved 2.0m, current_pos=(2.0, 0.0)"},\n'
'    {"role": "assistant", "content": "&lt;tool_call&gt;check_obstacle(direction=front)&lt;/tool_call&gt;"},\n'
'    {"role": "tool", "content": "no obstacle detected"}\n'
'  ],\n'
'  "reward_label": 0.78,\n'
'  "step_labels": [0.9, 0.85, 0.7, 0.8, 0.75],\n'
'  "dimension_scores": {\n'
'    "sequence_loss": 0.85, "arg_loss": 0.80, "forbidden_loss": 1.0,\n'
'    "final_text_loss": 0.70, "state_loss": 0.75, "behavior_loss": 0.80\n'
'  }\n'
'}</code></pre>\n'
'\n'
'<h3>4.2 推荐架构：混合 ORM + PRM</h3>\n'
'<p>针对具身导航 Agent 的特点（多轮工具调用、状态依赖、顺序约束），推荐采用混合 ORM + PRM 架构：</p>\n'
'\n'
'<pre><code class="language-python">class HybridRewardModel(nn.Module):\n'
'    def __init__(self, base_model, hidden_dim=768):\n'
'        super().__init__()\n'
'        self.encoder = base_model  # 共享 LLM 骨干（如 Qwen2.5-7B）\n'
'        # PRM 头：对每步工具调用打分\n'
'        self.prm_head = nn.Sequential(\n'
'            nn.Linear(hidden_dim, 256), nn.ReLU(),\n'
'            nn.Linear(256, 1), nn.Sigmoid()\n'
'        )\n'
'        # ORM 头：对完整轨迹打分\n'
'        self.orm_head = nn.Sequential(\n'
'            nn.Linear(hidden_dim, 256), nn.ReLU(),\n'
'            nn.Linear(256, 1), nn.Sigmoid()\n'
'        )\n'
'\n'
'    def forward(self, trajectory_tokens, step_boundaries):\n'
'        """\n'
'        trajectory_tokens: 完整轨迹的 token 序列\n'
'        step_boundaries: 每步工具调用结束位置的 token 索引列表\n'
'        """\n'
'        hidden_states = self.encoder(trajectory_tokens).last_hidden_state\n'
'        # PRM：提取每步工具调用结束位置的隐状态\n'
'        step_rewards = []\n'
'        for boundary_idx in step_boundaries:\n'
'            step_hidden = hidden_states[:, boundary_idx, :]\n'
'            step_rewards.append(self.prm_head(step_hidden))\n'
'        # ORM：使用序列末尾的隐状态\n'
'        r_episode = self.orm_head(hidden_states[:, -1, :])\n'
'        return r_episode, step_rewards\n'
'\n'
'    def compute_combined_reward(self, trajectory_tokens, step_boundaries,\n'
'                                 alpha=0.5, beta=0.5, gamma=0.9):\n'
'        r_episode, step_rewards = self.forward(trajectory_tokens, step_boundaries)\n'
'        T = len(step_rewards)\n'
'        discounted = sum((gamma**(T-t-1)) * step_rewards[t] for t in range(T))\n'
'        R = alpha * r_episode + beta * discounted\n'
'        return R, r_episode, step_rewards</code></pre>\n'
'\n'
'<p>混合奖励的数学形式：</p>\n'
'\\[\n'
'R(\\tau) = \\alpha \\cdot r_{\\text{episode}}(\\tau) + \\beta \\cdot \\sum_{t=1}^{T} \\gamma^{T-t} \\cdot r_{\\text{step}}(s_t, a_t, o_t)\n'
'\\]\n'
'<p>其中 \\( \\alpha + \\beta = 1 \\)，推荐初始值 \\( \\alpha = 0.5, \\beta = 0.5, \\gamma = 0.9 \\)。随着训练进行，可逐渐增大 \\( \\alpha \\)（更依赖 ORM 的全局判断）。</p>\n'
'\n'
'<h3>4.3 与 Sandbox 六维度的对应关系</h3>\n'
'<table>\n'
'  <thead>\n'
'    <tr><th>Sandbox 维度</th><th>权重</th><th>奖励模型组件</th><th>建模方式</th><th>说明</th></tr>\n'
'  </thead>\n'
'  <tbody>\n'
'    <tr><td><code>sequence_loss</code></td><td>0.35–0.40</td><td>PRM：工具选择分数</td><td>神经 PRM，步骤级</td><td>每步工具调用是否选择了正确的工具类型</td></tr>\n'
'    <tr><td><code>arg_loss</code></td><td>0.25–0.30</td><td>PRM：参数质量分数</td><td>神经 PRM，步骤级</td><td>工具调用参数的精度，可用连续值建模</td></tr>\n'
'    <tr><td><code>forbidden_loss</code></td><td>0.15</td><td>硬约束（保留规则式）</td><td>规则检查，二值</td><td>安全约束，不应被神经网络软化</td></tr>\n'
'    <tr><td><code>final_text_loss</code></td><td>0.05</td><td>ORM：语义完成分数</td><td>神经 ORM，轨迹级</td><td>最终输出的语义质量，需要全局上下文</td></tr>\n'
'    <tr><td><code>state_loss</code></td><td>0.10</td><td>ORM：状态一致性分数</td><td>神经 ORM，轨迹级</td><td>最终状态是否符合预期，依赖完整轨迹</td></tr>\n'
'    <tr><td><code>behavior_loss</code></td><td>0.10</td><td>PRM：行为顺序分数</td><td>神经 PRM，步骤级</td><td>顺序约束可在每步后立即检查</td></tr>\n'
'  </tbody>\n'
'</table>\n'
'\n'
'<div class="note">\n'
'  <strong>设计原则</strong>：<code>forbidden_loss</code> 保留为规则式硬约束，因为安全约束不应被神经网络"学习绕过"。其余五个维度均可用神经网络建模，以获得更好的泛化能力。\n'
'</div>\n'
'\n'
'<h3>4.4 可微分接入 GRPO/PPO</h3>\n'
'<p>混合奖励模型可通过三种方案接入 RL 训练，适用于不同的场景需求：</p>\n'
'\n'
'<h4>方案 A：ORM 作为 Verifier，接入标准 GRPO</h4>\n'
'<p>ORM 产出 \\([0,1]\\) 的连续分数，通过组内归一化转为优势估计，接入标准 GRPO：</p>\n'
'<pre><code class="language-python">def grpo_with_orm(policy, orm, prompts, group_size=8, beta=0.01):\n'
'    """方案 A：ORM 作为 Verifier 接入 GRPO，适合短轨迹（&lt;10 turns）"""\n'
'    all_losses = []\n'
'    for prompt in prompts:\n'
'        trajectories = [policy.generate(prompt) for _ in range(group_size)]\n'
'        rewards = torch.tensor([orm(tau) for tau in trajectories])\n'
'        # 组内归一化（GRPO 核心）\n'
'        normalized = (rewards - rewards.mean()) / (rewards.std() + 1e-8)\n'
'        for tau, A_hat in zip(trajectories, normalized):\n'
'            log_probs = policy.log_prob(tau, prompt)\n'
'            ref_log_probs = policy.ref_log_prob(tau, prompt)\n'
'            kl = (log_probs - ref_log_probs).sum()\n'
'            all_losses.append(-(A_hat * log_probs.sum()) + beta * kl)\n'
'    return torch.stack(all_losses).mean()</code></pre>\n'
'\n'
'<h4>方案 B：PRM 产出 Dense Reward，接入 MT-GRPO</h4>\n'
'<p>PRM 为每个 turn 提供步骤级奖励，接入 MT-GRPO（Multi-Turn GRPO）的 turn-level advantage 计算：</p>\n'
'<pre><code class="language-python">def mt_grpo_with_prm(policy, prm, orm, prompts, group_size=8,\n'
'                      alpha=0.5, beta_kl=0.01, gamma=0.9):\n'
'    """方案 B：PRM Dense Reward 接入 MT-GRPO，适合长轨迹（10-30 turns）"""\n'
'    all_losses = []\n'
'    for prompt in prompts:\n'
'        trajectories = [policy.generate_multiturn(prompt) for _ in range(group_size)]\n'
'        for tau in trajectories:\n'
'            T = len(tau.turns)\n'
'            step_rewards = [prm(tau, t) for t in range(T)]\n'
'            episode_reward = orm(tau)\n'
'            combined = [alpha * episode_reward + (1-alpha) * step_rewards[t]\n'
'                        for t in range(T)]\n'
'            advantages = compute_gae(combined, gamma=gamma, lam=0.95)\n'
'            for t, (turn, A_t) in enumerate(zip(tau.turns, advantages)):\n'
'                log_probs = policy.log_prob_turn(turn, tau.context_up_to(t))\n'
'                ref_log_probs = policy.ref_log_prob_turn(turn, tau.context_up_to(t))\n'
'                kl = (log_probs - ref_log_probs).sum()\n'
'                all_losses.append(-(A_t * log_probs.sum()) + beta_kl * kl)\n'
'    return torch.stack(all_losses).mean()\n'
'\n'
'def compute_gae(rewards, gamma=0.9, lam=0.95):\n'
'    """广义优势估计（Generalized Advantage Estimation, GAE）"""\n'
'    T = len(rewards)\n'
'    advantages, gae = [0.0]*T, 0.0\n'
'    for t in reversed(range(T)):\n'
'        next_val = rewards[t+1] if t &lt; T-1 else 0\n'
'        delta = rewards[t] + gamma * next_val - rewards[t]\n'
'        gae = delta + gamma * lam * gae\n'
'        advantages[t] = gae\n'
'    return advantages</code></pre>\n'
'\n'
'<h4>方案 C：GRADE 可微分奖励，端到端梯度传播</h4>\n'
'<p>使用 Gumbel-Softmax 松弛，实现奖励模型梯度直接传回 policy 参数：</p>\n'
'<pre><code class="language-python">def grade_differentiable_reward(policy, reward_model, prompts,\n'
'                                  temperature=1.0, beta_kl=0.01):\n'
'    """方案 C：GRADE 可微分奖励，适合端到端联合训练"""\n'
'    all_losses = []\n'
'    for prompt in prompts:\n'
'        logits_seq = policy.forward(prompt)  # shape: (T, vocab_size)\n'
'        soft_tokens = []\n'
'        for logits in logits_seq:\n'
'            # Gumbel-Softmax 松弛（保持可微分）\n'
'            gumbel = -torch.log(-torch.log(torch.rand_like(logits) + 1e-20) + 1e-20)\n'
'            soft_tokens.append(F.softmax((logits + gumbel) / temperature, dim=-1))\n'
'        # 软化 token 嵌入\n'
'        soft_embs = [(s.unsqueeze(0) @ reward_model.embedding_matrix)\n'
'                     for s in soft_tokens]\n'
'        soft_traj = torch.cat(soft_embs, dim=1)\n'
'        reward = reward_model.score(soft_traj)  # 梯度可传回 logits\n'
'        with torch.no_grad():\n'
'            hard_tokens = logits_seq.argmax(dim=-1)\n'
'        kl = (policy.log_prob(hard_tokens, prompt)\n'
'              - policy.ref_log_prob(hard_tokens, prompt)).sum()\n'
'        all_losses.append(-reward + beta_kl * kl)\n'
'    return torch.stack(all_losses).mean()</code></pre>\n'
'\n'
'<table>\n'
'  <thead>\n'
'    <tr><th>方案</th><th>梯度质量</th><th>实现复杂度</th><th>适用轨迹长度</th><th>奖励信号密度</th></tr>\n'
'  </thead>\n'
'  <tbody>\n'
'    <tr><td>方案 A：ORM + GRPO</td><td>中（REINFORCE 估计）</td><td>低</td><td>短（&lt;10 turns）</td><td>稀疏（轨迹级）</td></tr>\n'
'    <tr><td>方案 B：PRM + MT-GRPO</td><td>高（turn-level advantage）</td><td>中</td><td>中长（10-30 turns）</td><td>密集（步骤级）</td></tr>\n'
'    <tr><td>方案 C：GRADE 可微分</td><td>最高（直接梯度）</td><td>高</td><td>任意</td><td>密集（token 级）</td></tr>\n'
'  </tbody>\n'
'</table>\n'
'</section>\n'
)

with open(path, "a", encoding="utf-8") as f:
    f.write(content)
print("Section 4 written successfully")
