import os

path = "C:/Users/mousongzhe/NoteBook/agent_reward_report.html"

content = (
'<section id="comparison">\n'
'<h2>6. 方法对比与选择建议</h2>\n'
'\n'
'<p>针对具身机器人导航 Agent 的不同训练阶段和资源约束，以下表格对四种主要奖励模型方案进行系统对比：</p>\n'
'\n'
'<table>\n'
'  <thead>\n'
'    <tr>\n'
'      <th>方案</th>\n'
'      <th>适用场景</th>\n'
'      <th>数据需求</th>\n'
'      <th>梯度质量</th>\n'
'      <th>实现复杂度</th>\n'
'      <th>推荐 Loss 组合</th>\n'
'    </tr>\n'
'  </thead>\n'
'  <tbody>\n'
'    <tr>\n'
'      <td><strong>仅 ORM</strong></td>\n'
'      <td>短轨迹（&lt;10 turns），快速验证阶段</td>\n'
'      <td>中（需要轨迹级偏好对，约 5k 对）</td>\n'
'      <td>中（REINFORCE 估计，方差高）</td>\n'
'      <td>低（单头 LLM + BT 损失）</td>\n'
'      <td>BT Loss + GRPO + KL 惩罚</td>\n'
'    </tr>\n'
'    <tr>\n'
'      <td><strong>仅 PRM</strong></td>\n'
'      <td>步骤可独立评估的任务，信用分配困难场景</td>\n'
'      <td>高（需要步骤级标注，MC rollout 成本高）</td>\n'
'      <td>高（密集奖励，低方差）</td>\n'
'      <td>中（MC rollout 标注 + 步骤级训练）</td>\n'
'      <td>MSE/BCE Loss + MT-GRPO + GAE</td>\n'
'    </tr>\n'
'    <tr>\n'
'      <td><strong>ORM + PRM 混合</strong>（推荐）</td>\n'
'      <td>中长轨迹（10-30 turns），生产环境</td>\n'
'      <td>高（需要两种标注，但可共享骨干模型）</td>\n'
'      <td>高（密集 + 全局信号互补）</td>\n'
'      <td>中（双头架构，联合训练）</td>\n'
'      <td>BT + MSE + MT-GRPO/GAGPO + KL</td>\n'
'    </tr>\n'
'    <tr>\n'
'      <td><strong>可微分 RM（GRADE）</strong></td>\n'
'      <td>端到端优化，RM 与 policy 联合训练</td>\n'
'      <td>低（无需显式标注，直接优化）</td>\n'
'      <td>最高（直接梯度传播）</td>\n'
'      <td>高（Gumbel-Softmax + 联合训练）</td>\n'
'      <td>GRADE Loss + 直接梯度 + KL</td>\n'
'    </tr>\n'
'  </tbody>\n'
'</table>\n'
'\n'
'<h3>6.1 针对 Sandbox 场景的具体建议</h3>\n'
'\n'
'<h4>阶段一：快速验证（1-2 周）</h4>\n'
'<p>使用<strong>仅 ORM + 标准 GRPO</strong>方案：</p>\n'
'<ol>\n'
'  <li>用 sandbox 生成 5k 条轨迹，<code>score_trace</code> 自动标注</li>\n'
'  <li>构造 2k 偏好对，训练 ORM（Qwen2.5-7B 骨干，Bradley-Terry 损失）</li>\n'
'  <li>验证 ORM 与 <code>score_trace</code> 的 Spearman 相关性（目标 &gt; 0.75）</li>\n'
'  <li>接入 GRPO 训练，观察 policy 在 sandbox 上的分数提升</li>\n'
'</ol>\n'
'\n'
'<h4>阶段二：性能提升（3-4 周）</h4>\n'
'<p>升级为<strong>混合 ORM + PRM + MT-GRPO</strong>方案：</p>\n'
'<ol>\n'
'  <li>在阶段一数据基础上，增加 MC rollout 步骤级标注（每条轨迹 5 次 rollout）</li>\n'
'  <li>训练 PRM（与 ORM 共享骨干，双头架构）</li>\n'
'  <li>切换到 MT-GRPO，使用 turn-level advantage</li>\n'
'  <li>加入 PRIME 隐式 PRM 作为辅助奖励，防止奖励 hacking</li>\n'
'</ol>\n'
'\n'
'<h4>阶段三：长序列优化（5-8 周）</h4>\n'
'<p>针对 30+ turns 的复杂导航任务，升级为<strong>GAGPO + DataPRM</strong>方案：</p>\n'
'<ol>\n'
'  <li>引入 DataPRM 三元标签，区分探索性试错和真正错误</li>\n'
'  <li>使用 GAGPO 的 clip 机制处理长序列的梯度稳定性</li>\n'
'  <li>实现 WebRL 风格的自进化课程：每 10 次迭代更新奖励模型</li>\n'
'  <li>可选：引入 BranPO 的分支对比采样，精确定位关键决策点</li>\n'
'</ol>\n'
'\n'
'<h3>6.2 关键超参数建议</h3>\n'
'<table>\n'
'  <thead>\n'
'    <tr><th>超参数</th><th>推荐值</th><th>说明</th></tr>\n'
'  </thead>\n'
'  <tbody>\n'
'    <tr><td>ORM 权重 \\( \\alpha \\)</td><td>0.4–0.6</td><td>初始 0.5，随训练进行逐渐增大</td></tr>\n'
'    <tr><td>PRM 权重 \\( \\beta \\)</td><td>0.4–0.6</td><td>\\( \\alpha + \\beta = 1 \\)</td></tr>\n'
'    <tr><td>时间折扣 \\( \\gamma \\)</td><td>0.85–0.95</td><td>长轨迹用较小值（0.85），短轨迹用较大值（0.95）</td></tr>\n'
'    <tr><td>KL 惩罚 \\( \\beta_{\\text{KL}} \\)</td><td>0.01–0.05</td><td>初始 0.01，若出现奖励 hacking 则增大</td></tr>\n'
'    <tr><td>GRPO 组大小 \\( G \\)</td><td>8–16</td><td>计算资源允许时用 16，资源受限用 8</td></tr>\n'
'    <tr><td>偏好对分数差阈值</td><td>0.25–0.35</td><td>差异太小的对训练信号弱，差异太大则样本稀少</td></tr>\n'
'    <tr><td>MC rollout 次数</td><td>5–10</td><td>5 次可接受，10 次标签更准确但成本翻倍</td></tr>\n'
'    <tr><td>Gumbel 温度（GRADE）</td><td>从 1.0 退火到 0.1</td><td>训练初期高温保证梯度流动，后期低温接近离散采样</td></tr>\n'
'  </tbody>\n'
'</table>\n'
'\n'
'<h3>6.3 与现有 Differentiable RL Loss 的集成</h3>\n'
'<p>本报告的奖励模型方案与可微分 RL 损失报告中的各算法的集成关系如下：</p>\n'
'<table>\n'
'  <thead>\n'
'    <tr><th>RL 算法</th><th>推荐奖励模型</th><th>集成方式</th><th>适用场景</th></tr>\n'
'  </thead>\n'
'  <tbody>\n'
'    <tr><td>GRPO</td><td>ORM</td><td>ORM 输出作为组内归一化的奖励</td><td>短轨迹，快速验证</td></tr>\n'
'    <tr><td>Turn-PPO</td><td>PRM</td><td>PRM 输出作为每个 turn 的即时奖励</td><td>多轮对话，turn-level 优化</td></tr>\n'
'    <tr><td>MT-GRPO</td><td>ORM + PRM 混合</td><td>混合奖励 + GAE 计算 turn-level advantage</td><td>中长轨迹，推荐方案</td></tr>\n'
'    <tr><td>GAGPO</td><td>ORM + PRM 混合</td><td>密集 PRM 奖励 + GAGPO clip 机制</td><td>长序列，最优性能</td></tr>\n'
'    <tr><td>FRPO</td><td>ORM（作为约束）</td><td>ORM 分数作为可行性约束，FRPO 优化策略</td><td>有安全约束的场景</td></tr>\n'
'    <tr><td>GRADE</td><td>可微分 RM</td><td>Gumbel-Softmax 松弛，端到端梯度</td><td>端到端优化，高计算预算</td></tr>\n'
'  </tbody>\n'
'</table>\n'
'</section>\n'
)

with open(path, "a", encoding="utf-8") as f:
    f.write(content)
print("Section 6 written successfully")
