import os

path = "C:/Users/mousongzhe/NoteBook/agent_reward_report.html"

content = (
'<section id="training-pipeline">\n'
'<h2>5. 完整训练流程设计</h2>\n'
'\n'
'<h3>5.1 离线阶段：奖励模型训练</h3>\n'
'<p>奖励模型的训练分为数据生成、ORM 训练和 PRM 训练三个步骤：</p>\n'
'\n'
'<h4>步骤 1：用 Sandbox 生成训练数据</h4>\n'
'<pre><code class="language-python">def generate_training_data(sandbox, policy, num_tasks=1000, samples_per_task=10):\n'
'    """\n'
'    离线数据生成流程\n'
'    目标：生成 10k+ 条标注轨迹用于奖励模型训练\n'
'    """\n'
'    all_trajectories = []\n'
'    \n'
'    for task in sandbox.get_tasks(num_tasks):\n'
'        task_trajectories = []\n'
'        \n'
'        # 多温度采样，确保轨迹多样性\n'
'        for temperature in [0.3, 0.7, 1.0, 1.3]:\n'
'            for _ in range(samples_per_task // 4):\n'
'                tau = policy.generate(task.prompt, temperature=temperature)\n'
'                \n'
'                # sandbox 自动标注\n'
'                total_score, dim_scores = sandbox.score_trace(tau, task.reference)\n'
'                \n'
'                # 步骤级标注（MC rollout）\n'
'                step_labels = compute_step_labels_mc(\n'
'                    sandbox, policy, tau, task, num_rollouts=5\n'
'                )\n'
'                \n'
'                task_trajectories.append({\n'
'                    "trajectory": tau,\n'
'                    "total_score": total_score,\n'
'                    "dim_scores": dim_scores,\n'
'                    "step_labels": step_labels,\n'
'                })\n'
'        \n'
'        all_trajectories.extend(task_trajectories)\n'
'    \n'
'    return all_trajectories\n'
'\n'
'\n'
'def compute_step_labels_mc(sandbox, policy, tau, task, num_rollouts=5):\n'
'    """\n'
'    蒙特卡洛 rollout 标注步骤级奖励（类 Math-Shepherd）\n'
'    对轨迹中每个中间状态，从该状态出发采样 K 条完整轨迹\n'
'    用最终成功率作为该步的 PRM 标签\n'
'    """\n'
'    step_labels = []\n'
'    for t in range(len(tau.steps)):\n'
'        # 从第 t 步的状态出发，继续采样\n'
'        partial_context = tau.get_context_up_to(t)\n'
'        success_count = 0\n'
'        for _ in range(num_rollouts):\n'
'            completion = policy.generate_from_context(partial_context, task.prompt)\n'
'            full_tau = tau.steps[:t] + completion.steps\n'
'            score, _ = sandbox.score_trace(full_tau, task.reference)\n'
'            if score > 0.7:  # 成功阈值\n'
'                success_count += 1\n'
'        step_labels.append(success_count / num_rollouts)\n'
'    return step_labels</code></pre>\n'
'\n'
'<h4>步骤 2：训练 ORM（Bradley-Terry 对比损失）</h4>\n'
'<pre><code class="language-python">def train_orm(orm_model, preference_pairs, num_epochs=3, lr=1e-5):\n'
'    """\n'
'    ORM 训练：Bradley-Terry 偏好模型\n'
'    输入：偏好对列表 [(tau_pos, tau_neg)]\n'
'    """\n'
'    optimizer = torch.optim.AdamW(orm_model.parameters(), lr=lr)\n'
'    \n'
'    for epoch in range(num_epochs):\n'
'        total_loss = 0\n'
'        for batch in DataLoader(preference_pairs, batch_size=16, shuffle=True):\n'
'            tau_pos = batch["trajectory_pos"]\n'
'            tau_neg = batch["trajectory_neg"]\n'
'            \n'
'            # 前向传播\n'
'            r_pos = orm_model(tau_pos)  # shape: (batch,)\n'
'            r_neg = orm_model(tau_neg)  # shape: (batch,)\n'
'            \n'
'            # Bradley-Terry 损失\n'
'            # L = -E[log sigma(r_pos - r_neg)]\n'
'            loss = -F.logsigmoid(r_pos - r_neg).mean()\n'
'            \n'
'            # 可选：加入分数差异加权\n'
'            score_diff = batch["score_diff"]\n'
'            loss = -(score_diff * F.logsigmoid(r_pos - r_neg)).mean()\n'
'            \n'
'            optimizer.zero_grad()\n'
'            loss.backward()\n'
'            torch.nn.utils.clip_grad_norm_(orm_model.parameters(), 1.0)\n'
'            optimizer.step()\n'
'            total_loss += loss.item()\n'
'        \n'
'        print(f"Epoch {epoch+1}: ORM Loss = {total_loss:.4f}")\n'
'    \n'
'    return orm_model</code></pre>\n'
'\n'
'<h4>步骤 3：训练 PRM（步骤级回归损失）</h4>\n'
'<pre><code class="language-python">def train_prm(prm_model, step_labeled_data, num_epochs=3, lr=1e-5):\n'
'    """\n'
'    PRM 训练：步骤级 MSE 回归\n'
'    输入：带步骤标签的轨迹数据\n'
'    """\n'
'    optimizer = torch.optim.AdamW(prm_model.parameters(), lr=lr)\n'
'    \n'
'    for epoch in range(num_epochs):\n'
'        total_loss = 0\n'
'        for batch in DataLoader(step_labeled_data, batch_size=8, shuffle=True):\n'
'            trajectory_tokens = batch["trajectory_tokens"]\n'
'            step_boundaries = batch["step_boundaries"]\n'
'            step_labels = batch["step_labels"]  # shape: (batch, T)\n'
'            \n'
'            # 前向传播\n'
'            _, step_rewards = prm_model(trajectory_tokens, step_boundaries)\n'
'            step_rewards_tensor = torch.stack(step_rewards, dim=1)  # (batch, T)\n'
'            \n'
'            # MSE 损失（也可用 BCE）\n'
'            loss = F.mse_loss(step_rewards_tensor.squeeze(-1), step_labels)\n'
'            \n'
'            optimizer.zero_grad()\n'
'            loss.backward()\n'
'            torch.nn.utils.clip_grad_norm_(prm_model.parameters(), 1.0)\n'
'            optimizer.step()\n'
'            total_loss += loss.item()\n'
'        \n'
'        print(f"Epoch {epoch+1}: PRM Loss = {total_loss:.4f}")\n'
'    \n'
'    return prm_model</code></pre>\n'
'\n'
'<h4>步骤 4：验证奖励模型质量</h4>\n'
'<p>用 Spearman 相关系数验证神经奖励模型与 <code>score_trace</code> 的一致性：</p>\n'
'<pre><code class="language-python">from scipy.stats import spearmanr\n'
'\n'
'def validate_reward_model(orm_model, test_trajectories, sandbox):\n'
'    orm_scores = [orm_model(tau).item() for tau in test_trajectories]\n'
'    sandbox_scores = [sandbox.score_trace(tau, ref)[0]\n'
'                      for tau, ref in test_trajectories]\n'
'    corr, p_value = spearmanr(orm_scores, sandbox_scores)\n'
'    print(f"Spearman correlation: {corr:.4f} (p={p_value:.4f})")\n'
'    # 目标：corr > 0.8 表示奖励模型与 sandbox 高度一致\n'
'    return corr</code></pre>\n'
'\n'
'<h3>5.2 在线阶段：RL 训练</h3>\n'
'<p>根据轨迹长度和计算资源，选择不同的 RL 算法：</p>\n'
'\n'
'<h4>短轨迹（&lt; 10 turns）：GRPO with ORM Reward</h4>\n'
'<p>标准 GRPO 适合短轨迹场景，实现简单，计算开销低：</p>\n'
'\\[\n'
'\\mathcal{L}_{\\text{GRPO}} = -\\frac{1}{G} \\sum_{i=1}^{G} \\hat{A}_i \\log \\pi_\\theta(\\tau_i | x) + \\beta \\cdot \\text{KL}(\\pi_\\theta \\| \\pi_{\\text{ref}})\n'
'\\]\n'
'\\[\n'
'\\hat{A}_i = \\frac{r_{\\text{ORM}}(\\tau_i) - \\mu_r}{\\sigma_r}, \\quad \\mu_r = \\frac{1}{G}\\sum_j r_j, \\quad \\sigma_r = \\sqrt{\\frac{1}{G}\\sum_j (r_j - \\mu_r)^2}\n'
'\\]\n'
'\n'
'<h4>中长轨迹（10-30 turns）：MT-GRPO with PRM Reward</h4>\n'
'<p>MT-GRPO（Multi-Turn GRPO，arXiv:2505.11821）在每个 turn 计算独立的优势估计，解决长轨迹中的信用分配问题：</p>\n'
'\\[\n'
'\\mathcal{L}_{\\text{MT-GRPO}} = -\\sum_{t=1}^{T} \\hat{A}_t^{\\text{turn}} \\log \\pi_\\theta(a_t | s_t, c_t) + \\beta \\cdot \\text{KL}_t\n'
'\\]\n'
'<p>其中 \\( \\hat{A}_t^{\\text{turn}} \\) 为第 \\( t \\) 个 turn 的优势估计，由 PRM 的步骤级奖励通过 GAE 计算得到。</p>\n'
'\n'
'<h4>长序列（&gt; 30 turns）：GAGPO with Dense PRM</h4>\n'
'<p>GAGPO（Group Advantage Guided Policy Optimization）通过组内对比和密集 PRM 奖励，在长序列场景下取得最优性能：</p>\n'
'\\[\n'
'\\mathcal{L}_{\\text{GAGPO}} = -\\sum_{t=1}^{T} \\min\\left(\\rho_t \\hat{A}_t, \\text{clip}(\\rho_t, 1-\\epsilon, 1+\\epsilon) \\hat{A}_t\\right) + \\beta \\cdot \\text{KL}\n'
'\\]\n'
'<p>其中 \\( \\rho_t = \\pi_\\theta(a_t) / \\pi_{\\text{old}}(a_t) \\) 为重要性采样比，\\( \\epsilon \\) 为 PPO clip 参数。</p>\n'
'\n'
'<h4>训练流程总览</h4>\n'
'<pre><code class="language-python">def full_rl_training_pipeline(policy, orm, prm, sandbox,\n'
'                               num_iterations=100, trajectory_length_threshold=10):\n'
'    """\n'
'    完整 RL 训练流程\n'
'    自动根据轨迹长度选择合适的 RL 算法\n'
'    """\n'
'    for iteration in range(num_iterations):\n'
'        # 1. 采样轨迹\n'
'        prompts = sandbox.sample_tasks(batch_size=32)\n'
'        trajectories = [policy.generate_multiturn(p) for p in prompts]\n'
'        \n'
'        # 2. 计算奖励\n'
'        rewards = []\n'
'        for tau in trajectories:\n'
'            r_episode = orm(tau)\n'
'            r_steps = [prm(tau, t) for t in range(len(tau.turns))]\n'
'            # forbidden_loss 保留为规则式硬约束\n'
'            forbidden_penalty = sandbox.check_forbidden(tau)\n'
'            r_combined = 0.5 * r_episode + 0.5 * sum(r_steps) / len(r_steps)\n'
'            r_final = r_combined * (1 - forbidden_penalty)  # 违规则清零\n'
'            rewards.append(r_final)\n'
'        \n'
'        # 3. 根据轨迹长度选择 RL 算法\n'
'        avg_length = sum(len(tau.turns) for tau in trajectories) / len(trajectories)\n'
'        if avg_length &lt; trajectory_length_threshold:\n'
'            loss = grpo_with_orm(policy, orm, prompts)\n'
'        else:\n'
'            loss = mt_grpo_with_prm(policy, prm, orm, prompts)\n'
'        \n'
'        # 4. 反向传播\n'
'        loss.backward()\n'
'        optimizer.step()\n'
'        optimizer.zero_grad()\n'
'        \n'
'        # 5. 定期更新奖励模型（自进化课程，参考 WebRL）\n'
'        if iteration % 10 == 0:\n'
'            new_data = generate_training_data(sandbox, policy, num_tasks=100)\n'
'            orm = train_orm(orm, construct_preference_pairs(new_data))\n'
'            prm = train_prm(prm, new_data)\n'
'        \n'
'        print(f"Iter {iteration}: loss={loss.item():.4f}, avg_reward={sum(rewards)/len(rewards):.4f}")</code></pre>\n'
'\n'
'<h3>5.3 奖励 Hacking 防御</h3>\n'
'<p>奖励 Hacking（Reward Hacking）是 RL 训练中的核心风险：policy 学会欺骗奖励模型而非真正完成任务。以下三种防御策略可组合使用：</p>\n'
'\n'
'<h4>KL 惩罚</h4>\n'
'<p>在 RL 目标中加入与参考策略的 KL 散度惩罚，防止 policy 过度偏离预训练分布：</p>\n'
'\\[\n'
'\\mathcal{L}_{\\text{total}} = \\mathcal{L}_{\\text{RL}} + \\beta \\cdot \\text{KL}(\\pi_\\theta \\| \\pi_{\\text{ref}})\n'
'\\]\n'
'<p>推荐 \\( \\beta \\in [0.01, 0.05] \\)。\\( \\beta \\) 过大会限制 policy 的探索能力，\\( \\beta \\) 过小则无法防止奖励 hacking。</p>\n'
'\n'
'<h4>PRIME：隐式 PRM（避免奖励过拟合）</h4>\n'
'<p><strong>PRIME</strong>（arXiv:2502.01456）提出用语言模型本身的 token 概率作为隐式 PRM，避免显式训练 PRM 带来的过拟合风险：</p>\n'
'\\[\n'
'r_t^{\\text{PRIME}} = \\log \\frac{\\pi_{\\text{ref}}(a_t | s_t)}{\\pi_{\\text{base}}(a_t | s_t)}\n'
'\\]\n'
'<p>其中 \\( \\pi_{\\text{ref}} \\) 为经过 SFT 的参考策略，\\( \\pi_{\\text{base}} \\) 为预训练基础模型。这个比值衡量了 SFT 训练对该 token 的"偏好程度"，可作为步骤级奖励信号，无需额外训练 PRM。</p>\n'
'\n'
'<h4>DataPRM：三元奖励（区分探索性试错）</h4>\n'
'<p><strong>DataPRM</strong>（arXiv:2604.24198）提出三元奖励标签，区分三种步骤类型：</p>\n'
'<ul>\n'
'  <li><strong>正确步骤</strong>（+1）：直接推进任务完成的步骤</li>\n'
'  <li><strong>探索性试错</strong>（0）：虽然不是最优路径，但展现了合理的探索行为</li>\n'
'  <li><strong>错误步骤</strong>（-1）：导致任务失败或违反约束的步骤</li>\n'
'</ul>\n'
'<p>三元标签避免了将"探索性试错"惩罚为"错误"，鼓励 Agent 在不确定情况下进行合理探索。在 sandbox 场景中，可以通过分析步骤的最终影响来自动分配三元标签：</p>\n'
'<pre><code class="language-python">def assign_ternary_label(step, trajectory, sandbox, task):\n'
'    """\n'
'    DataPRM 三元标签分配\n'
'    +1: 正确步骤（该步后成功率显著提升）\n'
'     0: 探索性试错（该步后成功率未变或轻微下降，但步骤本身合理）\n'
'    -1: 错误步骤（该步后成功率显著下降，或违反约束）\n'
'    """\n'
'    # 计算该步前后的成功率变化\n'
'    success_before = estimate_success_rate(sandbox, trajectory[:step], task)\n'
'    success_after = estimate_success_rate(sandbox, trajectory[:step+1], task)\n'
'    delta = success_after - success_before\n'
'    \n'
'    # 检查是否违反约束\n'
'    if sandbox.check_forbidden_at_step(trajectory[step]):\n'
'        return -1  # 违反安全约束，直接标为错误\n'
'    \n'
'    if delta &gt; 0.1:\n'
'        return 1   # 显著提升，正确步骤\n'
'    elif delta &gt; -0.1:\n'
'        return 0   # 轻微变化，探索性试错\n'
'    else:\n'
'        return -1  # 显著下降，错误步骤</code></pre>\n'
'</section>\n'
)

with open(path, "a", encoding="utf-8") as f:
    f.write(content)
print("Section 5 written successfully")
